--编写一个嵌套事务。外层修改students表某记录，内层在teachers表插入一条记录。演示内层插入操作失败后，外层修改操作回滚
BEGIN TRAN UPD_STU
UPDATE STUDENTS SET GRADE = 2000 WHERE SID='800001216'
	BEGIN TRAN UPD_TEA
		INSERT INTO TEACHERS VALUES('123456780', '', '', '')
	IF @@ERROR != 0
		BEGIN
		ROLLBACK TRAN UPD_STU
		PRINT 'FAIL'
		RETURN 
		END
	COMMIT TRAN UPD_TEA
COMMIT TRAN UPD_STU
		
