/*
CREATE TABLE WORKER(
NUMBER CHAR(5),
NAME CHAR(8) CONSTRAINT U1 UNIQUE,
SEX CHAR(1),
SAGE INT CONSTRAINT U2 CHECK (SAGE<=28),
DEPARTMENT CHAR(20),
CONSTRAINT PK_WORKER PRIMARY KEY (NUMBER))

INSERT INTO WORKER VALUES('00001', 'LIYONG', 'M', 14, 'KEJIBU')
SELECT * FROM WORKER*/

/*
ALTER TABLE WORKER DROP U2
INSERT INTO WORKER 
VALUES('00002', 'WANGYONG', 'M', 38, 'KEJIBU')
SELECT * FROM WORKER*/

/*
GO 
CREATE RULE RULE_SEX AS @VALUE IN('F', 'M')
GO*/


--EXEC sp_bindrule RULE_SEX, 'WORKER.[SEX]'
--exec sp_unbindrule 'worker.[sex]' 
--INSERT INTO WORKER VALUES('00003', 'WANGHAO', '1', '25', 'YANFABU')

/*
GO
CREATE TRIGGER T1 ON WORKER
FOR INSERT, UPDATE
AS 
IF (SELECT SAGE FROM INSERTED) < 1
BEGIN
PRINT 'HHHHHHH'
ROLLBACK TRANSACTION
END
*/
--UPDATE WORKER
--SET SAGE = -100 WHERE NUMBER = '00001' 
--UPDATE  WORKER
--SET SAGE = -9
--WHERE NUMBER = '00001'
/*
CREATE PROCEDURE INSERTCOURSEINFO
	@COURSEID CHAR(10),
	@COURSENAME VARCHAR(30),
	@HOUR INT,
	@RETURNSTRING VARCHAR(100) OUT 
AS 
BEGIN TRAN
	IF EXISTS( SELECT CID FROM COURSES WHERE CID = @COURSEID)
		BEGIN
			SELECT @RETURNSTRING = 'EXISTED'
			GOTO ONERROR
		END
	INSERT INTO COURSES VALUES(@COURSEID, @COURSENAME, @HOUR)
	IF @@ERROR<>0
		BEGIN
			SELECT @RETURNSTRING='FAIL'
			GOTO ONERROR
		END
	SELECT @RETURNSTRING='SUCCESS'
	PRINT @RETURNSTRING
COMMIT TRAN
ONERROR:
	PRINT @RETURNSTRING
	ROLLBACK TRANSACTION
GO
*/
/*
DECLARE @COURSEID CHAR(10)
DECLARE @COURSENAME VARCHAR(30)
DECLARE @HOUR INT
DECLARE @RETURNSTRING VARCHAR(100)
EXEC INSERTCOURSEINFO '10051', 'ENGLISH', 90, @RETURNSTRING OUT
*/
--DROP PROCEDURE INSERTCOURSEINFO

/*
BEGIN TRAN TRAN_UPD_COURSES
	UPDATE COURSES
	SET hour=60
	WHERE cid='10001'
	BEGIN TRAN TRAN_UPD_TEACHERS
		INSERT INTO TEACHERS
		VALUES('1234567890', 'ZS', 'MY@ZSU.EDU.CN', 3000)
	IF @@ERROR != 0
		BEGIN
		ROLLBACK TRAN TRAN_UPD_TEACHER
		PRINT 'FAIL'
		RETURN
		END
	COMMIT TRAN TRAN_UPD_TEACHERS
	COMMIT TRAN TRAN_UPD_COURSES
*/
/*
SELECT * FROM COURSES
WHERE cid='10001'

BEGIN TRAN TRAN_UPD_COURSES
	UPDATE COURSES
	SET hour=46
	WHERE cid = '10001'
	
	SAVE TRAN TRAN_UPD_TEACHER_DONE
	INSERT INTO TEACHERS
	VALUES('1234567890', 'ZS', 'MY@ZSU.EDU.CN', 3000)
	IF @@ERROR !=0 OR @@ROWCOUNT > 1
		begin 
		ROLLBACK TRAN TRAN_UPD_TEACHER_DONE
		PRINT 'FAIL'
		RETURN 
		END
COMMIT TRANSACTION TRAN_UPD_COURSES
GO

SELECT * FROM COURSES
WHERE cid='10001'
*/
go 
BEGIN TRAN
	UPDATE TEACHERS SET salary=4200 WHERE tid='200003125'
	WAITFOR DELAY '00:00:10'
	SELECT * FROM TEACHERS WHERE tid='200003125'
ROLLBACK TRAN
	SELECT * from TEACHERS WHERE tid = '200003125'