--use school 
--create table Stu_Union(sno CHAR(5) NOT NULL UNIQUE,
--						SNAME CHAR(8),
--						SSEX CHAR(1),
--						SAGE INT,
--						SDEPT CHAR(20),
--						CONSTRAINT PK_STU_UNION PRIMARY KEY(SNO));
--INSERT Stu_Union VALUES ('10000', '王敏', '1', 23, 'CS');
--UPDATE Stu_Union SET sno = '' WHERE SDEPT='CS';
--UPDATE Stu_Union SET sno='95002' WHERE SNAME='王敏';
--SELECT * FROM Stu_Union;

/*
use School
create table class(CLASS_ID VARCHAR(4), NAME VARCHAR(10), DEPARTMENT VARCHAR(20),
					CONSTRAINT PK_CLASS_ID PRIMARY KEY(CLASS_ID));
*/					

--USE School
--INSERT STU_UNION VALUES ('95002', 'TOM', '1', 23, 'CS'); 

--USE School
--UPDATE STU_UNION SET SNO=NULL WHERE SNO='95002'

--USE School
--SET XACT_ABORT ON
--BEGIN TRANSACTION T1
--INSERT INTO STU_UNION VALUES ('95009', '李勇', 'M', 25, 'EE');
--INSERT INTO STU_UNION VALUES ('95003', '王浩', 'O', 25, 'EE');
--INSERT INTO STU_UNION VALUES ('95005', '王浩', 'O', 25, 'EE');
--SELECT * FROM STU_UNION;

/*
USE School
SET XACT_ABORT ON
BEGIN TRANSACTION T3
INSERT INTO CLASS VALUES('0001', '01CSC', 'CS');
BEGIN TRANSACTION T4
INSERT INTO CLASS VALUES('0001', '01CSC', 'CS');
*/


--INSERT INTO CLASS VALUES(NULL, '01CSC', 'CS');
--INSERT INTO CLASS VALUES('0002', '01CSC', 'CS');
--INSERT INTO CLASS VALUES('0002', '03CSC', 'CS');
--SELECT * FROM CLASS

/*
USE School
SET XACT_ABORT ON
BEGIN TRANSACTION T5
INSERT INTO CLASS VALUES('0003', '03CSC', 'CS');
INSERT INTO CLASS VALUES('0001', '03CSC', 'CS');
COMMIT TRANSACTION T5
*/

--seLECT * FROM CLASS

/*USE School
SET XACT_ABORT ON
BEGIN TRANSACTION T2
INSERT INTO STU_UNION VALUES('95007', '李明', 'M', 25, 'EE');
SELECT * FROM STU_UNION
INSERT INTO STU_UNION VALUES('95009', '李进', 'F', 22, 'CS');
COMMIT TRANSACTION T2*/

/*
USE School 
CREATE TABLE SCHOLARSHIP
(
	M_ID VARCHAR(10), STU_ID CHAR(10), R_MONEY INT
)
INSERT INTO SCHOLARSHIP VALUES ('0001', '700000', 5000)
INSERT INTO SCHOLARSHIP VALUES ('0001', '800000', 8000)
SELECT * FROM SCHOLARSHIP
*/

/*
USE School 
ALTER TABLE SCHOLARSHIP ADD
	CONSTRAINT PK_SCHOLARSHIP PRIMARY KEY(M_ID)
*/

/*
USE School
ALTER TABLE CLASS ADD
	CONSTRAINT PK_class PRIMARY KEY(NAME)
*/
/*
USE School
ALTER TABLE SCHOLARSHIP FOREIGN KEY(STU_ID) REFERENCES STUDENTS(SID)
*/

